@baseUrl = http://localhost:3333/api
@authToken = {{ login.response.body.data.access_token }}

###

# @name login
POST {{baseUrl}}/auth/login
content-type: application/json

{
  "username": "lennonc",
  "password": "1234"
}

###

# @name users
GET {{baseUrl}}/user/
content-type: application/json
Authorization: Bearer {{authToken}}

###

# @name user
GET {{baseUrl}}/user/1
content-type: application/json
Authorization: Bearer {{authToken}}

###

# @name createUser
POST {{baseUrl}}/user/
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "id": 4,
  "name": "Ozzy",
  "age": 6
}
